import Tkinter as tk

def createWindow():
    win = tk.Toplevel()
    win.title("Add an item")
    barcode = tk.Label(win, text = "BarCode:")
    win.geometry("300x200")
    barcode.grid(row=1, column = 0)
    barcodeEntry = tk.Entry(win)
    barcodeEntry.grid(row=1, column = 1, columnspan=3)
    ItemName = tk.Label(win, text="Product:")
    ItemName.grid(row=4,column = 0)
    ItemNameEntry = tk.Entry(win)
    ItemNameEntry.grid( row=4, column = 1, columnspan=3)
    CompanyName = tk.Label(win, text="Brand:")
    CompanyName.grid(row=7,column = 0)
    CompanyNameEntry = tk.Entry(win)
    CompanyNameEntry.grid(row=7, column = 1, columnspan=3)
    Price = tk.Label(win, text="Price:")
    Price.grid(row=10,column = 0)
    PriceEntry = tk.Entry(win)
    PriceEntry.grid(row=10, column = 1, columnspan=3)
    quant = tk.Label(win, text="Quantity:")
    quant.grid(row=13, column=0)
    quantity = tk.Entry(win)
    quantity.grid(row=13, column=1, columnspan=3)
    saveButton = tk.Button(win, text="SAVE")
    saveButton.grid(row = 15, column =1, columnspan=2)
